# docker-compose.yml

version: '3'

services:
  id-generator-1:
    build: ./id-generator
    environment:
      WORKER_ID: 1
      EPOCH: 1641052800000
    ports:
      - 5000
    networks:
      - snowflake-net

  id-generator-2:
    build: ./id-generator
    environment:
      WORKER_ID: 2
      EPOCH: 1641052800000
    ports:
      - 5000
    networks:
      - snowflake-net

  load-balancer-id-generators:
    image: nginx
    volumes:
      - ./id-generator-load-balancer/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    networks:
      - snowflake-net


  short-url-app:
    build:
      context: ./short-url
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGO_HOST=mongo
    networks:
      - snowflake-net

  mongodb:
    image: mongo
    container_name: 'mongodb'
    restart: always
    ports:
      - "27017:27017"
    networks:
      - snowflake-net

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
    networks:
      - snowflake-net
    depends_on:
      - mongodb
networks:
  snowflake-net:
