# docker-compose.yml

version: "3"

services:
  id-generator-1:
    build: ./id-generator
    environment:
      WORKER_ID: 1
      EPOCH: 1641052800000 #start date of timestamps
    ports:
      - "5002:5001"
    networks:
      - snowflake-net

  id-generator-2:
    build: ./id-generator
    environment:
      WORKER_ID: 2
      EPOCH: 1641052800000 #start date of timestamps
    ports:
      - "5003:5001"
    networks:
      - snowflake-net

  load-balancer-id-generators:
    image: nginx
    volumes:
      - ./id-generator-load-balancer/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    networks:
      - snowflake-net

  short-url-app:
    build:
      context: ./short-url
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
      - cache-container
    environment:
      MONGO_HOST: mongodb://mongodb:27017/
    networks:
      - snowflake-net

  mongodb:
    image: mongo
    container_name: "mongodb"
    restart: always
    ports:
      - "27017:27017"
    networks:
      - snowflake-net

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
    networks:
      - snowflake-net
    depends_on:
      - mongodb

  cache-container:
    build:
      context: ./cache
    image: memcached
    ports:
      - "11211:11211"
    environment:
      ME_CONFIG_MEMCACHE_URL: localhost:11211
    networks:
      - snowflake-net

networks:
  snowflake-net:
