# docker-compose.yml

version: '3'

services:
  id-generator-1:
    build: ./id-generator
    environment:
      WORKER_ID: 1
      EPOCH: 1641052800000 #start date of timestamps
    expose:
      - 5000
    networks:
      - snowflake-net

  id-generator-2:
    build: ./id-generator
    environment:
      WORKER_ID: 2
      EPOCH: 1641052800000 #start date of timestamps
    expose:
      - 5000
    networks:
      - snowflake-net

  load-balancer-id-generators:
    image: nginx
    volumes:
      - ./id-generator-load-balancer/nginx.conf:/etc/nginx/nginx.conf
    expose:
      - 80
    networks:
      - snowflake-net


  short-url-app:
    build:
      context: ./short-url
    expose:
      - 3000
    depends_on:
      - mongodb
      - memcached_http_server-load-balancer
    environment:
      - MONGO_HOST=mongodb://mongodb:27017/
    networks:
      - snowflake-net
    deploy:
      replicas: 3

  short-url-load-balancer:
    image: nginx
    ports:
      - "8080:80"
    depends_on:
      - short-url-app
    volumes:
      - ./short-url-load-balancer/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - snowflake-net
  

  mongodb:
    image: mongo
    container_name: 'mongodb'
    restart: always
    expose:
      - 27017
    networks:
      - snowflake-net

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
    networks:
      - snowflake-net
    depends_on:
      - mongodb

  memcached:
    image: memcached:latest
    container_name: memcached
    expose:
      - 11211
    networks:
      - snowflake-net

  memcached_http_server:
    build:
      context: ./cache-http-client
    depends_on:
      - memcached
    networks:
      - snowflake-net
    expose:
      - 8080
    environment:
      - PORT=8080
      - CACHE_SERVER=memcached:11211
    deploy:
      replicas: 3

  memcached_http_server-load-balancer:
    image: nginx
    expose:
      - 80
    volumes:
      - ./cache-http-client-load-balancer/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - snowflake-net
    depends_on:
      - memcached_http_server
 

networks:
  snowflake-net:
