version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.17
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Run tests
          command:  |
            cd id-generator
            go test

workflows:
  version: 2
  build:
    jobs:
      - build
